### PR TITLE
simplify output of deploy_suite()

### PR DESCRIPTION
**Pull request by floriankrb**

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/pyflow?pullRequest=17) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/pyflow?pullRequest=17) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/pyflow?pullRequest=17) it.</sub>

**Comment by corentincarton** [comment]
@floriankrb, we were in the process of revising the deployment process. We usually always deploy in the same target, meaning that (in my case), the overwrite option is always true. Do you have a case where you want this to fail if the files are already present?

**Comment by floriankrb** [comment]
Currently, when deploying a suite I have many warnings about files being overwritten. I am ignoring them because I consider that overwriting a file with identical content is ok. In such case, I wouldn't even consider it as overwriting and I would rather not have any message.

But if I was overwriting files with different content, I would like :
- either to have a warning.
- or to fail (if I want to make sure that I am not breaking other suites).

**Comment by corentincarton** [comment]
> Currently, when deploying a suite I have many warnings about files being overwritten. I am ignoring them because I consider that overwriting a file with identical content is ok. In such case, I wouldn't even consider it as overwriting and I would rather not have any message.
> 
> But if I was overwriting files with different content, I would like :
> 
> * either to have a warning.
> * or to fail (if I want to make sure that I am not breaking other suites).

Exactly. I don't think the warning is a good idea as it would be already too late if you care, the files would have been overwritten already. So I suggest the following:
- Put overwrite=True as default 
- If overwrite is False, then throw an error if the file already exists
Can you do your PR to the branch feature/git instead? Otherwise we'll conflict.

**Comment by corentincarton** [comment]
Sounds good. It would be interesting as we would then see what files are impacted by the change using overwrite=True. The thing is that I can't find a case where you wouldn't want to overwrite, unless you want to deploy each time in a clean target, but I don't really see what would be the point of doing that. That's why I believe it should be set to true by default.

**Comment by floriankrb** [comment]
Here is the pull request updated rebase on the correct feature branch.

 I will let you change the overwrite=False where it is appropriate.

**Pull request merged**
