### PR TITLE
Add latest ecFlow attributes: Aviso & Mirror

### PR DESCRIPTION
**Pull request by marcosbento**
This set of changes aligns pyflow with ecFlow 5.13.0.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/pyflow?pullRequest=49) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/pyflow?pullRequest=49) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/pyflow?pullRequest=49) it.</sub>

**Comment by marcosbento** [comment]
@corentincarton These changes only make sense when ecFlow 5.13.0 is available. Any suggestion on how to handle this dependency?

**Comment by corentincarton** [comment]
@marcosbento, can you put the >= 5.13.0 requirements in the environment.yml ? Careful we have another one in the doc folder (this should probably all go into the toml config actually).

Apart from that, are you ready to merge this branch?

**Review by corentincarton — APPROVED** [review]

**Comment by corentincarton** [comment]
@marcosbento. One last thing, could you add an example of usage in the documentation? For instance there: https://github.com/ecmwf/pyflow/blob/develop/docs/content/introductory-course/flow-control.ipynb

**Pull request merged**
